---
title: "Members"
description: |
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

- **Ruben Lennartz (Arslan)** (University of Leipzig)

   [Institutional website](https://www.lw.uni-leipzig.de/en/wilhelm-wundt-institute-for-psychology/working-groups-1/personality-psychology-and-psychological-assessment/team/dr-ruben-arslan-lennartz) | [Google Scholar]( https://scholar.google.de/citations?user=X6fXzMcAAAAJ&hl=de&oi=ao) | [ORCID](http://orcid.org/0000-0002-6670-5658)
- **Adam Ayaita** (RWTH Aachen University)

   [Institutional website](https://www.hrm.rwth-aachen.de/cms/HRM/Der-Lehrstuhl/Team/~ccjtr/Adam-Ayaita/?allou=1&lidx=1) | [Google Scholar]( https://scholar.google.de/citations?user=4qaWGE8AAAAJ&hl=de&oi=ao) | [ORCID](https://orcid.org/0000-0002-9975-3429)
- **Susanne Bücker** (Ruhr University Bochum)

   [Institutional website](https://www.pml.psy.ruhr-uni-bochum.de/personen/mitarb/b%C3%BCcker.html.en) | [Google Scholar](https://scholar.google.de/citations?hl=de&user=DxBhWPYAAAAJ) | [ORCID](https://orcid.org/0000-0003-3443-5400)
- **Tobias Ebert** (Mannheim Centre for European Social Research)

   [Institutional website](https://www.mzes.uni-mannheim.de/d7/en/profiles/tobias-ebert) | [Google Scholar](https://scholar.google.de/citations?user=muFfM98AAAAJ&hl=de&oi=ao) | [ORCID](https://orcid.org/0000-0003-0146-2517)
- **Michael P. Grosz** (Health and Medical University, Potsdam)

   [Institutional website](https://www.health-and-medical-university.de/universitaet/unser-team/team-fakultaet-gesundheit/professoren/prof-dr-michael-grosz/) | [Google Scholar](https://scholar.google.de/citations?user=zy0PqrEAAAAJ&hl=de&oi=ao) | [ORCID](https://orcid.org/0000-0002-1949-4384)
- **Sandrine Müller** (Google, New York City)

   [Personal website](https://www.sandrinermuller.com/) | [Google Scholar](https://scholar.google.de/citations?user=if1KQqgAAAAJ&hl=de&oi=ao)
- **Sven Rieger** (University of Tübingen)
   
   [Institutional website](https://uni-tuebingen.de/en/faculties/faculty-of-economics-and-social-sciences/subjects/department-of-social-sciences/education-sciences-and-psychology/institute/staff/rieger-sven-dr/) | [Google Scholar](https://scholar.google.de/citations?user=zIjPay4AAAAJ&hl=de&oi=ao) | [ORCID](https://orcid.org/0000-0002-0339-0695)   
- **Julia M. Rohrer** (University of Leipzig)

   [Institutional website](https://www.lw.uni-leipzig.de/en/wilhelm-wundt-institute-for-psychology/working-groups-1/personality-psychology-and-psychological-assessment/team/dr-julia-rohrer) | [Google Scholar](https://scholar.google.de/citations?user=Bg2qoJEAAAAJ&hl=de&oi=ao) | [ORCID](https://orcid.org/0000-0001-8564-4523)
- **Alexandra Zapko-Willmes** (University of Bremen)
  
   [Institutional website](https://www.uni-bremen.de/en/pppd/team/dr-alexandra-zapko-willmes) | [Google Scholar](https://scholar.google.de/citations?user=s3JV5DEAAAAJ&hl=de&oi=ao) | [ORCID](https://orcid.org/0000-0002-8489-2944)